### ISSUE TITLE
Makefile - Error 125

### ISSUE THREAD

**Issue by DeltaPh0** [DSecureMe/vmc-demo#3]
Hello,

I get an error after running the "make up" command. 

My configuration : 
- Debian 10
- docker-ce : 20.10.13
- docker compose : v2.2.3

Error :
**sudo sysctl -w vm.max_map_count=262144**
**vm.max_map_count = 262144**
**docker compose 	-f compose/docker-compose.postgresql.yml 	-f compose/docker-compose.elastalert.yml 	-f compose/docker-compose.hive.yml 	-f compose/docker-compose.elk.yml 	-f compose/docker-compose.vmc.yml 	-f compose/docker-compose.ralph.yml --env-file .env config**
**unknown shorthand flag: 'f' in -f**
**See 'docker --help'.**

**Run 'docker COMMAND --help' for more information on a command.**

**To get more help with docker, check out our guides at https://docs.docker.com/go/guides/**

**make: *** [Makefile:20: up] Error 125**

Thank you !

**Comment by mwalkowski** [comment]
Hello,

Thank you for submitting the issue.

I just verified the configuration and it works. Let me describe all steps I took.

**Reproduction steps**

- Installed Debian 11.3
- Added new user and added it to the sudoers group
- installed make
- Docker installation, followed [these steps](https://docs.docker.com/engine/install/debian/)
<img width="473" alt="image" src="https://user-images.githubusercontent.com/673031/162179055-b2a8c616-3f30-4a16-8b34-315941e13e72.png">
- Compose v2 installation, followed [these steps](https://docs.docker.com/compose/cli-command/)
<img width="473" alt="image" src="https://user-images.githubusercontent.com/673031/162179204-96b2b775-9095-45c7-8b2e-18eda1db805b.png">
**NOTE:**
Remember to install compose not as root, but as that new user you added to the sudoers group. Pay close attention to the [following steps](https://docs.docker.com/compose/cli-command/#install-on-linux)

- run `make up`

<img width="972" alt="image" src="https://user-images.githubusercontent.com/673031/162179359-d3d265e1-f0e8-4211-b52e-c13e380ac070.png">

Please let me know if it worked.

**Comment by DeltaPh0** [comment]
Hello,

Thank you for your answer. It was indeed a problem of rights permissions. The problem is now fixed.

Thanks again for your help.
