### ISSUE TITLE
Unable to reach vmc-admin panel

### ISSUE THREAD

**Issue by veanome** [DSecureMe/vmc-demo#4]
After successfully starting up the vmc-demo I am able to connect to Kibana , Ralph, and TheHive via their ports. However, I am unable to reach the vmc-admin panel via port 8080.

**Comment by mwalkowski** [comment]
Please download the dsecureme/vmc-static-nginx:1.0.2 image again, I fixed the error.

**Comment by veanome** [comment]
That seems to have fixed it, however I am now unable to login with the default username and password provided. Did one of those change?

**Comment by mwalkowski** [comment]
No, did you run `make demodata`?

**Comment by veanome** [comment]
Oh yeah, forgot to redo that part. All is working now. Thanks again!
